### ISSUE TITLE
[canvas] Overflowing characters are clipped by redrawn backgrounds

### ISSUE THREAD

**Issue by cpsdqs** [espterm/espterm-firmware#121]
- when redrawing, check for large characters and set needsUpdate for them too

![screenshot_20170909_162044](https://user-images.githubusercontent.com/2041118/30241145-da2a0c48-957d-11e7-95dd-2773eaf9f6ff.png)

some wide characters outside the redrawn region cause foreground stacking when repeatedly redrawn due to their neighbouring cell changing:
![screenshot_20170909_162424](https://user-images.githubusercontent.com/2041118/30241144-d719d7a4-957d-11e7-98b7-5d0988c8537d.png)

**Comment by c-probably-archived20260718** [comment]
Might've been fixed with https://github.com/espterm/espterm-front-end/commit/4731a259dd68cc20d486e8e1a751a7d9d02fa3c8 (please check)

**Comment by MightyPork** [comment]
the overlaying glitch is fixed, but there's at least one situation where the erase glitch remains:

I tested it with `🚉` 

![screenshot_20170910_175317](https://user-images.githubusercontent.com/2041118/30250585-1b12a070-9651-11e7-9003-b2b5bdbb7bf7.png) 
![screenshot_20170910_175322](https://user-images.githubusercontent.com/2041118/30250586-1e394d9e-9651-11e7-8ccd-2bd8d9e1d4f9.png) 
![screenshot_20170910_175359](https://user-images.githubusercontent.com/2041118/30250588-2052d500-9651-11e7-9b3c-35405a6a6186.png) 
![screenshot_20170910_175403](https://user-images.githubusercontent.com/2041118/30250589-235196c4-9651-11e7-9983-b9a01f0141f3.png)

it happens both on the same line and line above and below.

does not happen when it's neighbored by a non-blank character from the side closer to cursor

**Comment by c-probably-archived20260718** [comment]
Try now; you can see which characters are being updated by doing `Screen.window.debug = true` (one of the few benefits of having everything in global scope)

**Comment by MightyPork** [comment]
it's better! 

there is this small bug left, but i don't think it's worth wasting time on

(moved from the smiley leftwards)
![screenshot_20170910_190237](https://user-images.githubusercontent.com/2041118/30251167-ad510cde-965a-11e7-92f2-770b016b2322.png)

btw is it possible to enable sourcemaps for the babel minify plugin?

**Comment by c-probably-archived20260718** [comment]
Well, usually you'd be using webpack (which adds a few dozen bytes (obviously)) or something like gulp, which would do it for you. Though the `--source-maps` option does seem to work with the babel compiler, but not with the standalone minifier.

**Comment by c-probably-archived20260718** [comment]
so _is_ this fixed now? Because basically what I've done is just increase the radius of redrawn cells each time

**Comment by MightyPork** [comment]
not really, but it's better than it was before.

eg this bug is still there - `😛` with 1 space in between
![screenshot_20170910_205403](https://user-images.githubusercontent.com/2041118/30251956-3fd45aac-966a-11e7-9a41-d43d164d2a89.png)

**Comment by MightyPork** [comment]
is clipping expensive? because you could just set clip region and redraw all surrounding wide cells after redrawing the insides

or maybe not idk

**Comment by MightyPork** [comment]
oh, and that character disappearing bug from before with the train station is still there, but it's now y+2 and y-2 lines lol

but it's ok, printing emojis is not really a v important feature imo

**Comment by c-probably-archived20260718** [comment]
I don't get how your image with 😛 came to be (unless you disabled debug mode halfway through) because as far as I can see the entire region is being redrawn correctly, yet it still has strange clipping. And no, clipping shouldn't be expensive; I guess I could rewrite that part some time soon

**Comment by MightyPork** [comment]
Yeah I had debugging enabled before and switched it off cause that magenta overlay was obscuring my experiments

**Comment by c-probably-archived20260718** [comment]
...I would rewrite the debug mode to use a second overlay canvas that shows the updates, but wasn't this whole thing under some sort of size limit or something?

**Comment by MightyPork** [comment]
I have about 200 more kilobytes of ROM to spare, but if it could be removed
from the production build somehow that would be better ofc.

The bigger issue is RAM, which is elegantly worked around by throwing the
hard work at the browser

**Comment by c-probably-archived20260718** [comment]
oh wow you could at least fit half a percent of the node_modules folder in there
and also use webpack, or babel in case you do want to support the Android 4.4.4 or less browser

**Comment by c-probably-archived20260718** [comment]
~So as it turns out, clipping _is_ rather expensive, at least with the current algorithm (which sweeps each line and then adds horizontal regions to the mask; the fewer regions, the better) with 156ms for a full redraw vs 19ms without. Thus I disabled it by default, but it can be enabled by setting `Screen.window.graphics` to `1` (or higher)~ Needs more testing; but disabled by default

https://github.com/espterm/espterm-front-end/commit/de897f013c9259a59e0e357a8c9ea3203c384763

**Comment by MightyPork** [comment]
Works great with graphics=2, a full redraw time here is max 46 ms (in Chrome).

worse than 19, but pretty good.
maybe we can enable/disable it dynamically based on the presence of wide characters on the screen (most of the time that won't be the case, and if they are there, it's usually some static UI like a meteo-station panel with weather symbols)

i'll make a new issue for the dynamic switch, this looks fixed to me with the option
